In [15]:
import pandas as pd
import seaborn as sns

In [16]:
data=pd.read_csv("Cardiotocographic.csv")

In [17]:
df=pd.DataFrame(data)
df.sample(5) #This gives me some random rows data
#if we use this df.head() we wi;; get only first 5 rows data

,LB,AC,FM,UC,DL,DS,DP,ASTV,MSTV,ALTV,MLTV,Width,Tendency,NSP
67,140.0,0.007278,0.000000,0.004367,0.000000,0.0,0.0,34.0,1.2,0.000000,10.3,60.000000,0.0,1.0
60,146.0,0.005083,-0.002304,0.005083,0.000000,0.0,0.0,39.0,0.9,18.000000,5.2,44.375735,0.0,5.0
607,148.0,0.008323,0.004756,0.003567,0.000000,0.0,0.0,73.0,0.7,0.000000,9.9,82.000000,0.0,1.0
1327,128.0,0.005268,0.010536,0.004390,0.005268,0.0,0.0,30.0,1.7,0.000000,7.0,118.000000,0.0,1.0
686,133.0,0.000000,0.013661,0.005464,0.000000,0.0,0.0,29.0,1.3,0.537726,15.6,34.000000,0.0,1.0

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   LB        2105 non-null   float64
 1   AC        2106 non-null   float64
 2   FM        2126 non-null   float64
 3   UC        2126 non-null   float64
 4   DL        2126 non-null   float64
 5   DS        2105 non-null   float64
 6   DP        2105 non-null   float64
 7   ASTV      2126 non-null   float64
 8   MSTV      2126 non-null   float64
 9   ALTV      2126 non-null   float64
 10  MLTV      2105 non-null   float64
 11  Width     2105 non-null   float64
 12  Tendency  2105 non-null   float64
 13  NSP       2105 non-null   float64
dtypes: float64(14)
memory usage: 232.7 KB

In [19]:
#we do have missing values in here in this data 
df.isnull().sum()

LB          21
AC          20
FM           0
UC           0
DL           0
DS          21
DP          21
ASTV         0
MSTV         0
ALTV         0
MLTV        21
Width       21
Tendency    21
NSP         21
dtype: int64

In [ ]:
#iam dropping this missing values because 
#This missing values are less than 1 percent of the data we have
df.dropna(inplace=True)

In [33]:
df.shape #we have about 2123 rows of data

(2105, 14)

In [ ]:
df.isnull().sum() #null are removed

In [37]:
df.describe()
#This gives me statistical summary for every numerical row

,LB,AC,FM,UC,DL,DS,DP,ASTV,MSTV,ALTV,MLTV,Width,Tendency,NSP
count,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000,2105.000000
mean,133.343598,0.003202,0.009963,0.004388,0.001892,0.000003,0.000175,46.996929,1.361006,10.353647,8.284887,70.429260,0.316371,1.304507
std,11.270154,0.004324,0.067870,0.003350,0.003348,0.000142,0.000840,18.847737,1.173164,21.282102,7.772858,42.931822,0.645622,0.644619
min,51.842487,-0.019284,-0.480634,-0.014925,-0.015393,-0.001353,-0.005348,-63.000000,-6.600000,-91.000000,-50.700000,-174.000000,-3.000000,-1.025988
25%,126.000000,0.000000,0.000000,0.001838,0.000000,0.000000,0.000000,32.000000,0.700000,0.000000,4.600000,37.000000,0.000000,1.000000
50%,133.000000,0.001631,0.000000,0.004484,0.000000,0.000000,0.000000,49.000000,1.200000,0.000000,7.400000,67.000000,0.000000,1.000000
75%,140.000000,0.005650,0.002554,0.006536,0.003289,0.000000,0.000000,61.000000,1.700000,11.000000,10.900000,100.000000,1.000000,1.000000
max,214.000000,0.038567,0.961268,0.030002,0.030769,0.002706,0.010695,162.000000,13.800000,182.000000,101.400000,357.000000,3.000000,5.000000

In [ ]:
summary = pd.DataFrame({
    "Mean": df.mean(),
    "Median": df.median(),
    "Std_Dev": df.std(),
    "IQR": df.quantile(0.75) - df.quantile(0.25)
})

summary
#summary even more detailed

                Mean      Median    Std_Dev        IQR
LB        133.343598  133.000000  11.270154  14.000000
AC          0.003202    0.001631   0.004324   0.005650
FM          0.009963    0.000000   0.067870   0.002554
UC          0.004388    0.004484   0.003350   0.004698
DL          0.001892    0.000000   0.003348   0.003289
DS          0.000003    0.000000   0.000142   0.000000
DP          0.000175    0.000000   0.000840   0.000000
ASTV       46.996929   49.000000  18.847737  29.000000
MSTV        1.361006    1.200000   1.173164   1.000000
ALTV       10.353647    0.000000  21.282102  11.000000
MLTV        8.284887    7.400000   7.772858   6.300000
Width      70.429260   67.000000  42.931822  63.000000
Tendency    0.316371    0.000000   0.645622   1.000000
NSP         1.304507    1.000000   0.644619   0.000000

In [48]:
df.value_counts('NSP')

NSP
 1.000000    1546
 2.000000     280
 3.000000     164
-1.000000       5
 5.000000       4
             ...
 3.007324       1
 3.015185       1
 3.019152       1
 3.020038       1
 3.034545       1
Name: count, Length: 111, dtype: int64